#!/bin/bash -e

LIB=/usr/local/lib
SHARE=/usr/local/share
SRC=/usr/local/src

cd $SRC


# unpack electrum-LTC
tar -zxf Electrum-LTC-*.tar.gz
rm Electrum-LTC-*.tar.gz

# install electrum-LTC
mv Electrum-LTC-*/ $SHARE/electrum-ltc/
sudo ln -s $SHARE/electrum-ltc/electrum-ltc /usr/local/bin/electrum-ltc
sudo chmod +x /usr/local/bin/electrum-ltc


# unpack electrum-dash
tar -zxf Electrum-DASH-*.tar.gz
rm Electrum-DASH-*.tar.gz
mv Electrum-DASH*/ $SHARE/electrum-dash/
unzip electrum-dash-packages.zip -d $SHARE/electrum-dash/
rm electrum-dash-packages.zip

# install electrum-dash
pyrcc4 $SHARE/electrum-dash/icons.qrc -o $SHARE/electrum-dash/gui/qt/icons_rc.py
#sudo python $SHARE/electrum-dash/setup.py install
sudo ln -s $SHARE/electrum-dash/electrum-dash /usr/local/bin/electrum-dash
sudo chmod +x /usr/local/bin/electrum-dash


# install electrum dependency python-typing
tar -zxf typing-*.tar.gz
rm typing-*.tar.gz
mv typing-*/ $SHARE/python-typing/
cd $SHARE/python-typing
sudo python3 setup.py install
cd $SRC

# unpack electrum
tar -zxf Electrum-*.tar.gz
rm Electrum-*.tar.gz

# install electrum
mv Electrum-*/ $SHARE/electrum/
sudo ln -s $SHARE/electrum/electrum /usr/local/bin/electrum
sudo chmod +x /usr/local/bin/electrum


# install electrum-dash dependencies
#mkdir $SHARE/electrum-dash/packages/
/bin/cp $SHARE/electrum/packages/* $SHARE/electrum-dash/packages/ -R
